import type { Metadata } from "next";

import "./globals.css";
import { Footer } from "./components";
import { Header } from "./components/Header";
import { Body } from "./components/Body";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      <Body>{children}</Body>
      <Footer />
    </html>
  );
}
